{{- if .Values.serviceMonitor.enabled }}
{{- range $name, $svc := .Values.services }}
{{- if eq $svc.kind "web" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "touchstone.fullname" $ }}-{{ $name }}
  labels:
    {{- include "touchstone.serviceLabels" (dict "root" $ "name" $name) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "touchstone.selectorLabels" (dict "root" $ "name" $name) | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.serviceMonitor.interval }}
      scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
{{- end }}
{{- end }}
{{- end }}
